(()=>{'use strict';
const root=document.getElementById('hkspot'),main=root.querySelector('#spot-main'),KEY='hkchat-finance-spot-v1',scenes=__SPOT_SCENES__;
const HOME_PHOTO=__SPOT_HOME_PHOTO__;
const themes=[{id:'bank',label:'銀行服務'},{id:'insurance',label:'保障諮詢'},{id:'group',label:'金融群組'}];
const paths={search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',arrow:'M5 12h14M13 6l6 6-6 6',back:'M19 12H5M11 6l-6 6 6 6',check:'m5 12 4 4L19 6',bulb:'M9 18h6M9 22h6M8 14a7 7 0 1 1 8 0c-1 1-1 2-1 4H9c0-2 0-3-1-4',spark:'m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4L12 3',book:'M12 21V5M3 3h5a4 4 0 0 1 4 2 4 4 0 0 1 4-2h5v16h-5a4 4 0 0 0-4 2 4 4 0 0 0-4-2H3z'};
const icon=n=>'<svg class="spot-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[n]||paths.search)+'"/></svg>';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={version:1,view:'home',themeId:'bank',sceneId:'bank',custom:'',found:[],lastFound:null,hint:null,textOpen:false},generationToken=0,loadingStage=0,toastTimer;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved?.version===1&&scenes.some(s=>s.id===saved.sceneId)){const scene=scenes.find(s=>s.id===saved.sceneId);state={...state,view:['home','play','result'].includes(saved.view)?saved.view:'home',themeId:themes.some(t=>t.id===saved.themeId)?saved.themeId:'bank',sceneId:scene.id,custom:typeof saved.custom==='string'?saved.custom.slice(0,40):'',found:scene.clues.filter(c=>Array.isArray(saved.found)&&saved.found.includes(c.id)).map(c=>c.id)}}}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,view:state.view==='loading'?'home':state.view,themeId:state.themeId,sceneId:state.sceneId,custom:state.custom,found:state.found}))}catch{}}
const current=()=>scenes.find(s=>s.id===state.sceneId)||scenes[0];
const themeLabel=id=>themes.find(t=>t.id===id)?.label||'生活日常';
function home(){return '<section class="p-photo-hero"><img class="p-photo-bg" src="'+HOME_PHOTO+'" alt="" aria-hidden="true" decoding="async"><div class="p-photo-copy"><span class="p-photo-kicker">金融日常，細節要望真啲</span><h1>金融大找茬</h1><p>一張生活照，你搵到幾多金融疑點？</p></div></section><section class="spot-home-box"><h2>今次想挑戰邊一幕？</h2><div class="spot-themes">'+themes.map(t=>'<button type="button" class="spot-theme" data-theme="'+t.id+'" aria-pressed="'+(state.themeId===t.id)+'">'+t.label+'</button>').join('')+'</div><label class="spot-custom-label" for="spot-custom">或者，寫一個你想睇嘅場景</label><input class="spot-custom" id="spot-custom" maxlength="40" value="'+esc(state.custom)+'" placeholder="例如：查詢戶口、了解保障、群組消息" autocomplete="off"><button type="button" class="spot-primary" data-action="generate">生成找茬挑戰 '+icon('spark')+'</button></section><div class="spot-how"><span>望真啲</span><span>點出細節</span><span>識一點金融</span></div><p class="spot-home-note">AI 圖像 · 預設情境演示</p>'}
function loading(){return '<button type="button" class="spot-back" data-action="home">'+icon('back')+' 換個主題</button><section class="spot-loading"><div class="spot-loading-art">'+icon('search')+'</div><h2>正在準備金融一幕</h2><p>'+esc(themeLabel(state.themeId))+'，有啲細節等你發現。</p><p class="spot-loading-stage" role="status">'+['整理場景細節…','加入值得留意的線索…','準備你的找茬挑戰…'][loadingStage]+'</p><p class="spot-muted">預設情境演示</p></section>'}
function hitStyle(r){return 'left:clamp(0px,calc('+(r.x+r.w/2)+'% - max('+(r.w/2)+'%,22px)),calc(100% - max('+r.w+'%,44px)));top:clamp(0px,calc('+(r.y+r.h/2)+'% - max('+(r.h/2)+'%,22px)),calc(100% - max('+r.h+'%,44px)));width:max('+r.w+'%,44px);height:max('+r.h+'%,44px)'}
function picture(){const c=current();return '<div class="spot-photo"><div class="spot-photo-canvas" style="--spot-image-ratio:'+c.width+'/'+c.height+'"><img class="spot-scene-image" src="'+c.src+'" width="'+c.width+'" height="'+c.height+'" alt="'+esc(c.alt)+'" decoding="async" draggable="false">'+c.clues.map(clue=>{const n=state.found.indexOf(clue.id),found=n!==-1;return '<button type="button" class="spot-hit'+(found?' spot-found':state.hint===clue.id?' spot-hint':'')+'" data-clue="'+esc(clue.id)+'" style="'+hitStyle(clue.rect)+'" aria-label="'+esc((found?'重溫：':'查看：')+clue.visualLabel)+'" aria-pressed="'+found+'">'+(found?'<span class="spot-number" style="'+(clue.rect.y<4?'top:4px;':'')+(clue.rect.x<4?'left:4px;':'')+'" aria-hidden="true">'+(n+1)+'</span>':'')+'</button>'}).join('')+'<span class="spot-photo-credit">AI 生成 · 虛構場景</span></div></div>'}
function discovery(){const c=current().clues.find(c=>c.id===state.lastFound);return c?'<section class="spot-discovery" role="status"><span class="spot-discovery-label">找到一處值得留意的細節</span><h3>'+esc(c.title)+'</h3><p>'+esc(c.explanation)+'</p></section>':''}
function textChoices(){const c=current(),options=[];c.clues.forEach((clue,i)=>{options.push({...clue,answer:true});if(c.decoys?.[i])options.push(c.decoys[i])});return options.map(option=>'<button type="button" class="spot-text-choice" '+(option.answer?'data-clue':'data-decoy')+'="'+esc(option.id)+'" aria-pressed="'+(option.answer&&state.found.includes(option.id))+'"><span>'+esc(option.visualLabel)+'</span>'+icon(option.answer&&state.found.includes(option.id)?'check':'arrow')+'</button>').join('')}
function customContext(){return state.custom.trim()?'<p class="spot-custom-context">題材配對：<span>'+esc(state.custom.trim())+'</span></p>':''}
function play(){const c=current();return '<button type="button" class="spot-back" data-action="home">'+icon('back')+' 換個主題</button><div class="spot-play-top"><span class="spot-theme-tag">'+esc(themeLabel(c.id))+'</span><span class="spot-counter" aria-live="polite">已找到 <strong>'+state.found.length+'</strong> / 3</span></div>'+customContext()+'<h2 class="spot-play-title">'+esc(c.title)+'</h2><p class="spot-play-subtitle">'+esc(c.subtitle)+'</p>'+picture()+'<div class="spot-photo-helper"><span>點畫面，搵出 3 處值得留意的細節</span></div><div class="spot-actions"><button type="button" class="spot-secondary" data-action="hint"'+(state.found.length===3?' disabled':'')+'>'+icon('bulb')+' 畀個提示</button><button type="button" class="spot-primary" data-action="answers">看看答案 '+icon('arrow')+'</button></div>'+discovery()+'<details class="spot-text-mode"'+(state.textOpen?' open':'')+'><summary>想用文字找？</summary><div class="spot-text-options">'+textChoices()+'</div></details>'}
function result(){const c=current(),n=state.found.length;return '<button type="button" class="spot-back" data-action="play">'+icon('back')+' 返回畫面</button><section class="spot-result-hero"><div class="spot-result-score">今次搵到 <strong>'+n+' / 3</strong> 處</div><h2>'+({0:'一齊望真啲',1:'你已經捉到重點',2:'差少少，全中！',3:'好眼利，全部搵到！'}[n])+'</h2><p>'+esc(c.title)+'，有以下細節值得了解。</p></section><div class="spot-results">'+c.clues.map((clue,i)=>'<article class="spot-risk"><div class="spot-risk-top"><span class="spot-risk-index">細節 '+(i+1)+'</span><span class="spot-result-tag'+(state.found.includes(clue.id)?'':' spot-missed')+'">'+(state.found.includes(clue.id)?'你搵到':'再望真啲')+'</span></div><h3>'+esc(clue.title)+'</h3><p>'+esc(clue.explanation)+'</p><a class="spot-source" href="'+esc(clue.sourceUrl)+'" target="_blank" rel="noopener noreferrer">'+icon('book')+'<span>'+esc(clue.sourceTitle)+'</span></a></article>').join('')+'</div><p class="spot-result-note">以上為虛構情境的知識解說；發現疑點後，記得核實來源與完整條件。</p><div class="spot-result-actions"><button type="button" class="spot-primary" data-action="next">換個 AI 場景 '+icon('spark')+'</button><button type="button" class="spot-secondary" data-action="home">自己揀個主題</button></div>'}
function render(top=false){root.querySelector('.spot-toast')?.remove();clearTimeout(toastTimer);main.innerHTML=state.view==='home'?home():state.view==='loading'?loading():state.view==='result'?result():play();root.dataset.view=state.view;if(top)window.scrollTo({top:0,behavior:'instant'})}
function toast(message){root.querySelector('.spot-toast')?.remove();clearTimeout(toastTimer);const element=document.createElement('div');element.className='spot-toast';element.setAttribute('role','status');element.textContent=message;root.appendChild(element);toastTimer=setTimeout(()=>element.remove(),2100)}
function chooseScene(){const custom=state.custom.trim().toLowerCase();return (custom&&scenes.find(s=>(s.keywords||[]).some(k=>custom.includes(k.toLowerCase()))))||scenes.find(s=>s.id===state.themeId)||scenes[0]}
async function generate(next=false){const token=++generationToken;if(next){const i=scenes.findIndex(s=>s.id===state.sceneId);state.themeId=scenes[(i+1)%scenes.length].id;state.custom=''}const c=chooseScene();state.themeId=c.id;state.sceneId=c.id;state.found=[];state.lastFound=null;state.hint=null;state.textOpen=false;state.view='loading';loadingStage=0;save();render(true);for(let i=0;i<3;i++){await new Promise(resolve=>setTimeout(resolve,500));if(token!==generationToken)return;loadingStage=Math.min(i+1,2);if(i<2){const stage=main.querySelector('.spot-loading-stage');if(stage)stage.textContent=['整理場景細節…','加入值得留意的線索…','準備你的找茬挑戰…'][loadingStage]}}if(token!==generationToken)return;state.view='play';save();render(true)}
function findClue(id){const clue=current().clues.find(c=>c.id===id);if(!clue)return;const textChoice=document.activeElement?.classList.contains('spot-text-choice');state.textOpen=!!main.querySelector('.spot-text-mode[open]');if(!state.found.includes(id))state.found.push(id);state.lastFound=id;if(state.hint===id)state.hint=null;const y=window.scrollY;save();render();window.scrollTo(0,y);main.querySelector((textChoice?'.spot-text-choice':'.spot-hit')+'[data-clue="'+CSS.escape(id)+'"]')?.focus({preventScroll:true})}
root.addEventListener('toggle',e=>{if(e.target.classList?.contains('spot-text-mode'))state.textOpen=e.target.open},true);
root.addEventListener('input',e=>{if(e.target.id==='spot-custom'){state.custom=e.target.value.slice(0,40);save()}});
root.addEventListener('keydown',e=>{if(e.target.id==='spot-custom'&&e.key==='Enter'){e.preventDefault();generate()}});
root.addEventListener('click',e=>{const button=e.target.closest('button');if(button&&root.contains(button)){if(button.dataset.theme){state.themeId=button.dataset.theme;state.custom='';save();render();main.querySelector('[data-theme="'+CSS.escape(state.themeId)+'"]')?.focus({preventScroll:true});return}if(button.dataset.clue&&state.view==='play'){findClue(button.dataset.clue);return}if(button.dataset.decoy&&state.view==='play'){toast('再望真啲，留意其他細節');return}const action=button.dataset.action;if(action==='home'){++generationToken;state.view='home';state.hint=null;state.lastFound=null;save();render(true);return}if(action==='generate'){generate();return}if(action==='next'){generate(true);return}if(action==='hint'&&state.view==='play'){const remaining=current().clues.filter(c=>!state.found.includes(c.id));if(!remaining.length)return;const index=remaining.findIndex(c=>c.id===state.hint);state.hint=remaining[(index+1)%remaining.length].id;const y=window.scrollY;render();window.scrollTo(0,y);toast('可以留意畫面中亮起的地方');return}if(action==='answers'&&state.view==='play'){state.view='result';save();render(true);return}if(action==='play'&&state.view==='result'){state.view='play';state.lastFound=null;save();render(true);return}}if(state.view==='play'&&e.target.closest('.spot-photo-canvas'))toast('留意畫面中的細節')});
render();
})();
