const main=document.getElementById('role-main'),root=document.getElementById('hkroles');
const E=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=id=>({view:'home',id:id||DATA.cases[0].id,index:0,draft:'',selected:null,records:[],trialIndex:0,trial:null});
let s=fresh(),pending=null;
const scene=()=>DATA.cases.find(c=>c.id===s.id)||DATA.cases[0];
const stage=()=>scene().stages[s.view==='practice'?s.trialIndex:s.index];
const labels={clear:'講清楚了',partial:'可再補一句',overclaim:'需要澄清',custom:'自訂文字 · 待覆核'};
const btn=(label,act,secondary=false,extra='')=>'<button type="button" class="'+(secondary?'cv-secondary':'cv-primary')+'" data-act="'+act+'" '+extra+'>'+label+'</button>';
const badge=kind=>'<span class="ins-badge ins-badge-'+E(kind)+'">'+E(labels[kind])+'</span>';
const note=()=>'<p class="cv-disclosure">虛構客戶與簡化練習卡 · 只作溝通練習。客戶回應按預設選項演示，自訂文字不作自動判讀；未接即時 AI。內容只留在此頁，重新整理會清除。</p>';
const homeLink=()=>'<a class="ins-back" href="index.html">‹ 返回首頁</a>';
const say=text=>{document.getElementById('ins-announcer').textContent=text};
function render(html,focus=true){main.innerHTML=html;root.dataset.view=s.view;if(focus){main.querySelector('h1,h2')?.setAttribute('tabindex','-1');main.querySelector('h1,h2')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}}
function facts(){return '<details class="cv-facts"><summary>打開今局練習卡 · 3 個重點</summary><div class="cv-fact-list">'+scene().facts.map(f=>'<article class="cv-fact"><strong>'+E(f.title)+'</strong><p>'+E(f.text)+'</p></article>').join('')+'<p class="ins-prompt">'+E(scene().context)+'</p></div></details>'}
function sources(){return '<details class="cv-disclosure"><summary>了解更多 · 一般保險知識</summary><p>一般概念參考保監局教育資料；本局人物與保障卡是虛構設定，並非真實產品或機構認可。</p>'+DATA.sources.map(x=>'<a href="'+E(x.url)+'" target="_blank" rel="noopener noreferrer">'+E(x.name)+' ↗</a>').join('')+'</details>'}
function customer(){const c=scene();return '<div class="ins-customer"><span class="ins-avatar" aria-hidden="true">'+E(c.customer.name.slice(-1))+'</span><div><strong>'+E(c.customer.name)+'</strong><small>'+E(c.customer.identity)+'</small></div></div>'}
function bubble(text,label){return '<section class="cv-call"><span>'+E(label||scene().customer.name+' · 虛構客戶')+'</span><p>'+E(text)+'</p></section>'}
function tags(items){return '<div class="ins-fact-tags">'+items.map(x=>'<span>'+E(x)+'</span>').join('')+'</div>'}
function home(){s.view='home';render(homeLink()+'<section class="ins-hero"><img src="'+DATA.photo+'" alt="AI 生成的香港辦公室保險顧問與客戶會面情境"><div><div class="cv-kicker">換上保險顧問視角</div><h1>今日我做保險顧問</h1><p>聽到客人需要，先講得入心。<br>範圍、限制同選擇，一樣講清楚。</p><div class="ins-meta"><span>3 輪會面</span><span>約 3 分鐘</span><span>隨時收尾</span></div></div></section><p class="ins-home-copy">今次你坐喺顧問嗰邊。先聽客人想了解甚麼，再解釋虛構方案，睇吓對方點接話。</p><h2 class="cv-home-heading">今日先見邊位客人？</h2><div class="cv-cases">'+DATA.cases.map(c=>'<button type="button" class="cv-case" data-case="'+E(c.id)+'"><span>'+E(c.tag)+' · '+E(c.customer.name)+'</span><strong>'+E(c.title)+'</strong><small>'+E(c.desc)+'</small><span class="cv-start-hint">入座，開始會面 →</span></button>').join('')+'</div>'+note())}
function top(){return '<div class="cv-topline"><button type="button" class="cv-back" data-act="change">‹ 換位客人</button><span class="cv-muted">第 '+(s.index+1)+' / 3 輪</span></div><ol class="cv-progress" aria-label="會面進度">'+['問需要','講範圍','解疑慮'].map((x,i)=>'<li'+(i===s.index?' aria-current="step"':'')+'>'+x+'</li>').join('')+'</ol>'}
function choices(){return '<div class="ins-choices" role="group" aria-label="選擇你的說法">'+stage().choices.map(c=>'<button type="button" class="ins-choice" data-choice="'+E(c.id)+'" aria-pressed="'+(s.selected===c.id)+'"><strong>'+E(c.label)+'</strong><span>'+E(c.text)+'</span></button>').join('')+'</div><details class="ins-compose"><summary>想用自己的說法？點此改寫</summary><label class="cv-field" for="ins-draft"><span>我的說法</span><textarea id="ins-draft" maxlength="700" placeholder="先揀一句起稿，或者寫低自己的說法。">'+E(s.draft)+'</textarea></label><p class="ins-prompt">改寫內容只會記錄原文，列作待覆核；客戶接話只對應完整預設句。</p></details><p class="ins-draft-note" id="ins-selection">'+(s.selected?'已揀好說法，可以回應客人。':s.draft.trim()?'使用自訂說法，將保留原文。':'先揀一句，或者寫下你的說法。')+'</p><p class="cv-error" id="ins-error" role="alert"></p>'}
function history(){return s.records.length?'<details class="cv-log"><summary>回看已完成對話（'+s.records.length+' 輪）</summary>'+s.records.map((r,i)=>'<article><strong>第 '+(i+1)+' 輪 · 我的說法</strong><p>'+E(r.text)+'</p><strong>'+E(r.kind==='custom'?'未模擬客戶接話':scene().customer.name)+'</strong><p>'+E(r.reply||'保留自訂文字，待覆核。')+'</p></article>').join('')+'</details>':''}
function meeting(){s.view='meeting';const c=scene(),t=stage();render(top()+customer()+'<p class="cv-kicker">'+E(c.tag)+'</p><h1>'+E(t.title)+'</h1>'+(s.index===0?'<p class="ins-opening">入座時，'+E(c.customer.name)+'說：「'+E(c.customer.opening)+'」</p>':'')+bubble(t.prompt)+'<p class="ins-prompt">'+E(t.context)+'</p>'+facts()+'<h2 class="cv-home-heading cv-gap">你會點講？</h2>'+choices()+'<div class="cv-actions">'+btn('回應客人 →','submit')+btn('先收尾，睇目前紀錄','finish',true)+'</div>'+history()+note())}
function match(text){return stage().choices.find(c=>c.text.trim()===text.trim())}
function assess(text){const c=match(text);return c?{text:text.trim(),choiceId:c.id,kind:c.kind,reply:c.reply,coach:c.coach,evidence:c.evidence,trial:null}:{text:text.trim(),choiceId:null,kind:'custom',reply:'',coach:'你改寫的內容已原樣保留，演示不會推斷客戶反應，也不會評估是否講得正確。可參考本輪方向，或重練時試一句預設說法。',evidence:[],trial:null}}
function feedback(r){return '<div class="cv-panel"><span class="cv-kicker">我剛才的說法</span><p class="cv-answer cv-gap-sm">'+E(r.text)+'</p></div>'+(r.reply?bubble(r.reply):'<div class="cv-panel"><strong>自訂回應已記下</strong><p class="cv-muted cv-gap-sm">這段沒有對應的預設接話；客戶反應未作模擬。</p></div>')+'<aside class="cv-coach">'+badge(r.kind)+'<p class="cv-gap-sm">'+E(r.coach)+'</p>'+tags(r.evidence)+'</aside>'}
function response(){s.view='response';const r=s.records[s.index];render(top()+customer()+'<p class="cv-kicker">'+E(stage().title)+'</p><h1>客人點樣接話？</h1>'+feedback(r)+'<div class="cv-actions">'+btn(s.index===2?'整理這次會面':'進入下一輪 →','next')+(s.index<2?btn('先收尾，睇目前紀錄','finish',true):'')+'</div>'+note())}
function report(){s.view='result';const c=scene(),done=s.records.length,needs=s.records.filter(r=>['partial','overclaim'].includes(r.kind)).length,unknown=s.records.some(r=>r.kind==='custom'),title=done<3?'今次先傾到呢度':needs?'有幾句，值得再講清楚':unknown?'自訂說法，留待覆核':'聽清需要，講清選擇。';render(homeLink()+'<section class="cv-result-title"><span class="cv-kicker">會面練習紀錄</span><h1>'+title+'</h1><p class="cv-muted">'+E(c.title)+'</p><p class="ins-count">已回應 '+done+' / 3 輪 · 只記錄本局練習</p></section><p class="ins-home-copy">'+E(done?c.takeaway:'本局尚未提交回應，未有對話可回顧。')+'</p><h2>逐輪回看</h2>'+c.stages.map((t,i)=>{const r=s.records[i];if(!r)return '<div class="ins-unplayed">0'+(i+1)+' · '+E(t.title)+'<br>本輪未進行，沒有產生客戶回應或評語。</div>';return '<details class="ins-record" data-record="'+i+'"><summary><span>0'+(i+1)+'</span><strong>'+E(t.title)+'</strong>'+badge(r.kind)+'</summary><div><p class="cv-muted">客人問：'+E(t.prompt)+'</p>'+feedback(r)+'<div class="cv-coach"><strong>可以帶走的一句提醒</strong><p>'+E(t.guidance)+'</p></div>'+(r.trial?'<details class="cv-log"><summary>查看重練版本</summary><article><p>'+E(r.trial.text)+'</p>'+badge(r.trial.kind)+'<p>'+E(r.trial.coach)+'</p></article></details>':'')+'<div class="cv-actions">'+btn('換一種說法，重練這輪','practice',true,'data-index="'+i+'"')+'</div></div></details>'}).join('')+(done?'<aside class="cv-coach cv-gap"><strong>下次可以這樣練</strong><p>'+E(c.followup)+'</p></aside>':'')+'<div class="cv-actions">'+(done?btn('複製我的會面筆記','copy'):'')+(done<3?btn('繼續未完成的會面','resume',true):'')+btn('同一位客人，再試一次','restart',true)+btn('換一位客人','change',true)+'</div>'+sources()+note())}
function practice(i){s.view='practice';s.trialIndex=i;s.draft=s.records[i].trial?.text||s.records[i].text;s.selected=match(s.draft)?.id||null;s.trial=null;practiceView()}
function practiceView(){const r=s.records[s.trialIndex];render('<button type="button" class="ins-back" data-act="report">‹ 返回會面紀錄</button><p class="cv-kicker">重練第 '+(s.trialIndex+1)+' 輪 · 原對話會保留</p><h1>'+E(stage().title)+'</h1>'+bubble(stage().prompt)+facts()+choices()+'<div class="cv-actions">'+btn('看看另一種說法','save-trial')+'</div>'+(s.trial?'<section class="cv-gap"><h2>兩種說法，兩個回應</h2><div class="ins-compare">'+[{label:'原本',r},{label:'重練',r:s.trial}].map(x=>'<article><h3>'+x.label+'</h3>'+badge(x.r.kind)+'<p>'+E(x.r.text)+'</p><p class="cv-muted">'+E(x.r.reply||'自訂文字，未模擬客戶回應。')+'</p></article>').join('')+'</div><div class="cv-coach"><strong>重練提示</strong><p>'+E(s.trial.coach)+'</p></div><div class="cv-actions">'+btn('保留重練紀錄，返回復盤','report',true)+'</div></section>':'')+note())}
function error(text){const el=document.getElementById('ins-error');if(el){el.textContent=text;el.scrollIntoView({block:'center',behavior:'instant'})}say(text)}
function transcript(){const c=scene();return '今日我做保險顧問｜'+c.title+'\n虛構對話練習・預設回應，不代表真實保障或索償結果。\n'+c.stages.map((t,i)=>{const r=s.records[i];if(!r)return '\n第 '+(i+1)+' 輪：未進行。';return '\n第 '+(i+1)+' 輪｜'+t.title+'\n客人：'+t.prompt+'\n我：'+r.text+'\n'+(r.reply?'客人回應：'+r.reply:'自訂文字，未模擬客戶回應。')+'\n練習觀察：'+r.coach+(r.trial?'\n重練：'+r.trial.text+'\n重練提示：'+r.trial.coach:'')}).join('\n')}
function confirm(action,finish=false){pending=action;const d=document.getElementById('ins-confirm');d.querySelector('h2').textContent=finish?'先結束這次會面？':'重新開始這次會面？';d.querySelector('p').textContent=finish?'已提交對話會保留；目前未提交的草稿不會列入紀錄。':'將清除本局對話與重練紀錄。你可以先返回複製筆記。';d.showModal();d.querySelector('[data-confirm=cancel]').focus()}
function start(id){s=fresh(id);s.view='meeting';meeting()}
main.addEventListener('input',e=>{if(e.target.id!=='ins-draft')return;s.draft=e.target.value;s.selected=match(s.draft)?.id||null;main.querySelectorAll('[data-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.choice===s.selected)));document.getElementById('ins-selection').textContent=s.selected?'完整預設說法，將展示對應客戶回應。':'使用自訂說法，將保留原文，列作待覆核。';document.getElementById('ins-error').textContent=''});
main.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.case){start(b.dataset.case);return}
 if(b.dataset.choice){const c=stage().choices.find(x=>x.id===b.dataset.choice);if(!c)return;s.draft=c.text;s.selected=c.id;main.querySelectorAll('[data-choice]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.getElementById('ins-draft').value=s.draft;document.getElementById('ins-selection').textContent='已揀好「'+c.label+'」，可以回應客人。';document.getElementById('ins-error').textContent='';say('已選擇'+c.label);return}
 const a=b.dataset.act;
 if(a==='submit'&&s.view==='meeting'){if(s.draft.trim().length<8){error('先揀一句，或寫一句完整的說法。');return}s.records[s.index]=assess(s.draft);s.draft='';s.selected=null;response()}
 if(a==='next'&&s.view==='response'){if(s.index===2)report();else{s.index++;s.draft='';s.selected=null;meeting()}}
 if(a==='finish'){if(s.view==='meeting'&&s.draft.trim())confirm(report,true);else report()}
 if(a==='resume'){s.index=s.records.length;s.draft='';s.selected=null;meeting()}
 if(a==='practice')practice(Number(b.dataset.index));
 if(a==='save-trial'&&s.view==='practice'){if(s.draft.trim().length<8){error('先揀另一句，或寫一句完整的說法。');return}s.trial=assess(s.draft);s.records[s.trialIndex].trial=s.trial;practiceView();main.querySelector('.ins-compare')?.scrollIntoView({block:'start',behavior:'instant'});say('已保存重練版本，原對話保留。')}
 if(a==='report')report();
 if(a==='restart')confirm(()=>start(s.id));
 if(a==='change'){if(s.records.length||s.draft.trim())confirm(()=>{s=fresh();home()});else{s=fresh();home()}}
 if(a==='copy'){try{await navigator.clipboard.writeText(transcript());b.textContent='已複製會面筆記';say('筆記已複製。')}catch{b.textContent='未能複製，可長按選取對話';say('未能複製，可長按選取對話。')}}
});
document.getElementById('ins-confirm').addEventListener('click',e=>{const b=e.target.closest('[data-confirm]');if(!b)return;const action=pending;pending=null;document.getElementById('ins-confirm').close();if(b.dataset.confirm==='yes')action?.()});
document.getElementById('ins-confirm').addEventListener('cancel',()=>{pending=null});
home();
